# Generated by Django 4.0.3 on 2022-03-23 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SignChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('signature', models.TextField(blank=True)),
                ('pubkey', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdhaarRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('blood_type', models.CharField(max_length=3)),
                ('dob', models.DateField()),
                ('address', models.TextField()),
                ('photograph', models.ImageField(upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sign_challenge', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='core.signchallenge')),
            ],
        ),
    ]
