# Generated by Django 4.0.3 on 2022-05-02 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerifierRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_type', models.CharField(max_length=34)),
                ('attribute_groups', models.JSONField()),
                ('entropy', models.TextField()),
            ],
        ),
    ]
