# Generated by Django 4.0.3 on 2022-05-08 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_verifierrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='verifierrequest',
            name='token',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='verifierrequest',
            name='verifiable_presentation',
            field=models.JSONField(null=True),
        ),
    ]
