# Generated by Django 4.0.3 on 2022-05-21 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_verifierrequest_redirecturl'),
    ]

    operations = [
        migrations.AddField(
            model_name='adhaarrequest',
            name='is_fake',
            field=models.BooleanField(default=False),
        ),
    ]
